// data.js
// All balancing knobs live here first. The rest of the code tries to treat this
// file as the designer-facing spreadsheet for jobs, parts, labels, and flavor.

export const ENGINE = {
  name: "S20-DET Mule",
  inspiration: "SR20DET-inspired 2.0L turbo inline-four",
  displacementLiters: 2.0,
  stockWhp: 205,
  stockWtq: 200,
  idleRpm: 850,
  minRpm: 2200,
  stockRevLimit: 7200,
  hardRevLimit: 8600,
  stockBoostPsi: 10,
};

export const JOBS = [
  {
    id: "street-rescue",
    name: "Street Rescue",
    budget: 4200,
    hpMin: 285,
    hpMax: 335,
    responseTarget: 64,
    reliabilityMin: 72,
    maxFuelDuty: 92,
    maxKnock: 42,
    description:
      "Customer wants a clean street tune. Starts every morning, no hero pulls, no weird bucking in traffic. They will absolutely still do pulls leaving meets.",
    notes: ["Smooth curve", "Fast-ish spool", "Don't make it a grenade"],
  },
  {
    id: "drift-practice",
    name: "Drift Practice Day",
    budget: 6800,
    hpMin: 330,
    hpMax: 415,
    responseTarget: 58,
    reliabilityMin: 58,
    maxFuelDuty: 98,
    maxKnock: 55,
    description:
      "Needs enough torque to party but not so much lag that the car feels asleep between transitions. Tire budget is somehow bigger than maintenance budget.",
    notes: ["Responsive midrange", "Heat matters", "Some drama allowed"],
  },
  {
    id: "rally-ish",
    name: "Backroad Rally-ish",
    budget: 7200,
    hpMin: 305,
    hpMax: 375,
    responseTarget: 72,
    reliabilityMin: 76,
    maxFuelDuty: 90,
    maxKnock: 38,
    description:
      "Not a real rally car. Very much driven like one. Wants punch out of corners, cool intake temps, and a tune that does not hate long pulls uphill.",
    notes: ["Low heat", "Fast spool", "Safe timing"],
  },
  {
    id: "one-race",
    name: "One Race Wonder",
    budget: 6500,
    hpMin: 430,
    hpMax: 999,
    responseTarget: 30,
    reliabilityMin: 28,
    maxFuelDuty: 112,
    maxKnock: 78,
    description:
      "The customer said 'it only has to live tonight.' They also said 'reliable' twice, which is legally meaningless in this shop.",
    notes: ["Big number", "Survive the pull", "Morally questionable"],
  },
  {
    id: "dyno-queen",
    name: "Forum Dyno Queen",
    budget: 11800,
    hpMin: 500,
    hpMax: 999,
    responseTarget: 22,
    reliabilityMin: 38,
    maxFuelDuty: 108,
    maxKnock: 66,
    description:
      "The forum signature needs a 5xx whp graph. Street manners are optional. The comment section is not.",
    notes: ["Peak power", "Big turbo", "Screenshot bait"],
  },
];

export const PART_CATEGORIES = [
  {
    id: "turbo",
    label: "Turbocharger",
    options: [
      {
        id: "t25-stock",
        name: "Stock T25-ish",
        cost: 0,
        desc: "Tiny snail, instant vibes, out of breath up top.",
        airflow: 0.92,
        efficiency: 0.92,
        spoolRpm: 2850,
        boostCeiling: 15,
        heat: 1.15,
        stress: 0.82,
        response: 18,
      },
      {
        id: "t28-oem-plus",
        name: "OEM+ T28",
        cost: 950,
        desc: "The sensible upgrade. Quick spool, decent ceiling, hard to hate.",
        airflow: 1.08,
        efficiency: 1.02,
        spoolRpm: 3250,
        boostCeiling: 19,
        heat: 1.02,
        stress: 0.94,
        response: 12,
      },
      {
        id: "2871-street",
        name: "GT2871R Street Hero",
        cost: 1850,
        desc: "The answer half the internet was already typing.",
        airflow: 1.26,
        efficiency: 1.12,
        spoolRpm: 3850,
        boostCeiling: 24,
        heat: 1.04,
        stress: 1.08,
        response: 2,
      },
      {
        id: "3071-timeattack",
        name: "3071 Time Attack",
        cost: 2600,
        desc: "Lag tax paid in full. Pulls hard once it wakes up.",
        airflow: 1.42,
        efficiency: 1.16,
        spoolRpm: 4550,
        boostCeiling: 29,
        heat: 1.1,
        stress: 1.22,
        response: -12,
      },
      {
        id: "ebay-3076",
        name: "Auction 3076 Mystery Unit",
        cost: 760,
        desc: "Suspiciously cheap. Includes free compressor-map fan fiction.",
        airflow: 1.36,
        efficiency: 0.98,
        spoolRpm: 5050,
        boostCeiling: 27,
        heat: 1.32,
        stress: 1.3,
        response: -22,
        chaos: 18,
      },
    ],
  },
  {
    id: "fuel",
    label: "Fuel",
    options: [
      {
        id: "pump-91",
        name: "Pump 91",
        cost: 0,
        desc: "Available everywhere. Forgiveness not included.",
        knockResist: 0,
        power: 0.98,
        demand: 1.0,
        heat: 1.02,
      },
      {
        id: "pump-93",
        name: "Pump 93",
        cost: 80,
        desc: "A little more timing headroom. The boring correct choice.",
        knockResist: 8,
        power: 1.0,
        demand: 1.0,
        heat: 1.0,
      },
      {
        id: "e85",
        name: "E85",
        cost: 280,
        desc: "Big safety and power buff. Now your gas station is a side quest.",
        knockResist: 24,
        power: 1.08,
        demand: 1.32,
        heat: 0.88,
      },
    ],
  },
  {
    id: "injectors",
    label: "Injectors",
    options: [
      {
        id: "inj-370",
        name: "Stock 370 cc",
        cost: 0,
        desc: "Fine until it very suddenly is not fine.",
        whpCap: 260,
        control: -4,
      },
      {
        id: "inj-550",
        name: "550 cc Side-feed",
        cost: 420,
        desc: "OEM+ fueling for mild builds.",
        whpCap: 350,
        control: 0,
      },
      {
        id: "inj-740",
        name: "740 cc Nismo-ish",
        cost: 720,
        desc: "The classic street/track injector size.",
        whpCap: 455,
        control: 3,
      },
      {
        id: "inj-1000",
        name: "1000 cc Top-feed",
        cost: 1080,
        desc: "Plenty of fuel, slightly grumpy idle if tuned badly.",
        whpCap: 620,
        control: 5,
      },
    ],
  },
  {
    id: "pump",
    label: "Fuel Pump",
    options: [
      {
        id: "pump-stock",
        name: "Stock Pump",
        cost: 0,
        desc: "A museum piece with wires.",
        whpCap: 270,
        stability: -7,
      },
      {
        id: "pump-255",
        name: "255 LPH Pump",
        cost: 180,
        desc: "Cheap, common, good enough surprisingly often.",
        whpCap: 430,
        stability: 2,
      },
      {
        id: "pump-450",
        name: "450 LPH Pump",
        cost: 360,
        desc: "For when corn fuel enters the chat.",
        whpCap: 650,
        stability: 6,
      },
    ],
  },
  {
    id: "intercooler",
    label: "Intercooler",
    options: [
      {
        id: "smic-stock",
        name: "Stock Side Mount",
        cost: 0,
        desc: "Cute little heat sponge.",
        cooling: 0,
        pressureDrop: 0,
        spoolPenalty: 0,
      },
      {
        id: "fmic-street",
        name: "Street Front Mount",
        cost: 700,
        desc: "Cooler charge temps, small spool tax, looks correct.",
        cooling: 18,
        pressureDrop: 2,
        spoolPenalty: 120,
      },
      {
        id: "fmic-huge",
        name: "Big Front Mount",
        cost: 1050,
        desc: "Excellent cooling. There is a couch-sized object in the bumper now.",
        cooling: 28,
        pressureDrop: 4,
        spoolPenalty: 260,
      },
    ],
  },
  {
    id: "exhaust",
    label: "Exhaust",
    options: [
      {
        id: "exh-stock",
        name: "Stock Exhaust",
        cost: 0,
        desc: "Civilized. Restrictive. Emotionally safe.",
        airflow: 0,
        response: 0,
        heat: 4,
      },
      {
        id: "exh-catback",
        name: "Cat-back",
        cost: 520,
        desc: "More sound than science, still nice.",
        airflow: 8,
        response: 3,
        heat: 0,
      },
      {
        id: "exh-turboback",
        name: "Turbo-back",
        cost: 920,
        desc: "The turbo can finally exhale.",
        airflow: 18,
        response: 8,
        heat: -3,
      },
      {
        id: "exh-screamer",
        name: "Screamer Pipe Crimes",
        cost: 660,
        desc: "Noise complaint any%. Boost control vibes questionable.",
        airflow: 22,
        response: 9,
        heat: -2,
        chaos: 12,
      },
    ],
  },
  {
    id: "cams",
    label: "Cams",
    options: [
      {
        id: "cams-stock",
        name: "Stock Cams",
        cost: 0,
        desc: "Smooth, boring, honestly pretty good.",
        topEnd: 0,
        response: 6,
        idle: 0,
      },
      {
        id: "cams-256",
        name: "256/256 Poncam-ish",
        cost: 820,
        desc: "Streetable bump in top-end without ruining the car.",
        topEnd: 14,
        response: 2,
        idle: 2,
      },
      {
        id: "cams-264",
        name: "264 Step Cams",
        cost: 1050,
        desc: "More rev-happy, less polite.",
        topEnd: 24,
        response: -5,
        idle: 7,
      },
      {
        id: "cams-272",
        name: "272 Drag Cams",
        cost: 1280,
        desc: "Street manners have left the building.",
        topEnd: 36,
        response: -16,
        idle: 15,
      },
    ],
  },
  {
    id: "ecu",
    label: "ECU",
    options: [
      {
        id: "ecu-stock",
        name: "Stock ECU Hackery",
        cost: 0,
        desc: "You can make it work. Mostly.",
        control: 0,
        mapResolution: 0,
        safety: 0,
      },
      {
        id: "ecu-chipped",
        name: "Daughterboard Tune",
        cost: 520,
        desc: "Period-correct wizard rectangle.",
        control: 8,
        mapResolution: 8,
        safety: 5,
      },
      {
        id: "ecu-standalone",
        name: "Standalone ECU",
        cost: 1450,
        desc: "Real control. Real menus. Real ways to embarrass yourself.",
        control: 18,
        mapResolution: 18,
        safety: 14,
      },
    ],
  },
  {
    id: "bottomEnd",
    label: "Bottom End",
    options: [
      {
        id: "bottom-stock",
        name: "Stock Bottom End",
        cost: 0,
        desc: "Everyone says it holds 400. Everyone is very confident online.",
        torqueLimit: 360,
        boostComfort: 18,
        stressRelief: 0,
      },
      {
        id: "bottom-studs-gasket",
        name: "Studs + Head Gasket",
        cost: 1050,
        desc: "Doesn't make power. Lets you keep making power.",
        torqueLimit: 420,
        boostComfort: 23,
        stressRelief: 10,
      },
      {
        id: "bottom-forged",
        name: "Forged Bottom End",
        cost: 3600,
        desc: "Permission slip for terrible ideas.",
        torqueLimit: 610,
        boostComfort: 32,
        stressRelief: 28,
      },
    ],
  },
];

export const TUNE_CONTROLS = [
  {
    id: "boost",
    label: "Boost Target",
    min: 8,
    max: 30,
    step: 0.5,
    unit: "psi",
    defaultValue: 14,
    help: "More boost makes torque and heat. Hardware ceilings matter more than bravery.",
  },
  {
    id: "timing",
    label: "Ignition Advance",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
    defaultValue: 45,
    help: "Safe to spicy. Timing makes power until it starts making expensive sounds.",
  },
  {
    id: "fuelBias",
    label: "Fuel Bias",
    min: -50,
    max: 50,
    step: 1,
    unit: "",
    defaultValue: -8,
    help: "Left is richer/cooler. Right is leaner/crisper/riskier. This is not real AFR tuning.",
    formatter(value) {
      if (value < -8) return `${Math.abs(value)} rich`;
      if (value > 8) return `${value} lean`;
      return "near target";
    },
  },
  {
    id: "camBias",
    label: "Cam / VVT Bias",
    min: -50,
    max: 50,
    step: 1,
    unit: "",
    defaultValue: 0,
    help: "Left favors response and midrange. Right favors top-end dyno glory.",
    formatter(value) {
      if (value < -8) return `${Math.abs(value)} response`;
      if (value > 8) return `${value} top-end`;
      return "balanced";
    },
  },
  {
    id: "revLimit",
    label: "Rev Limit",
    min: 6800,
    max: 8600,
    step: 100,
    unit: "rpm",
    defaultValue: 7400,
    help: "More rpm can chase peak power, especially with cams. Stock valvetrain sends a concerned email.",
  },
  {
    id: "boostRamp",
    label: "Boost Ramp",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
    defaultValue: 48,
    help: "Smooth ramp protects parts. Violent ramp makes the graph look cool and the drivetrain nervous.",
  },
];

export const FAILURE_MESSAGES = {
  block: [
    "Your block has a new window.",
    "Cylinder 3 has become an atmospheric cylinder.",
    "The connecting rod has submitted its two-week notice.",
    "The SR heard 'send it' and took that personally.",
  ],
  knock: [
    "The knock sensor is writing a dissertation.",
    "Piston ringlands are now a subscription service.",
    "Detonation entered the chat with admin privileges.",
    "That timing map was a hate crime against aluminum.",
  ],
  fuel: [
    "Fuel pressure left early to beat traffic.",
    "Congratulations, you invented the lean sneeze any% route.",
    "Injector duty cycle says 'lol no'.",
    "The fuel system is filing a workplace complaint.",
  ],
  turbo: [
    "The turbo has reclassified itself as a smoke machine.",
    "Compressor efficiency has been replaced with vibes.",
    "Shaft play speedrun complete.",
    "The auction turbo was built from haunted pot metal.",
  ],
  heat: [
    "Intake temps are now soup.",
    "The head gasket lifted its skirt and ran away.",
    "Heat soak has achieved sentience.",
    "The intercooler is doing decorative labor only.",
  ],
};

export const SUCCESS_MESSAGES = [
  "Clean pull. The dyno operator did the respectful nod.",
  "Graph looks good. Customer is already asking if there is more in it.",
  "No drama. Weirdly suspicious.",
  "Smooth curve, solid number, no new holes. Huge day for the shop.",
];

export const WARNING_MESSAGES = [
  "It lived, but the log is making faces at you.",
  "Good number. Bad vibes.",
  "The customer says 'hell yeah.' The engine says 'please stop.'",
  "Technically successful in the same way jumping a curb is parking.",
];

export function defaultParts() {
  return Object.fromEntries(PART_CATEGORIES.map((category) => [category.id, category.options[0].id]));
}

export function defaultTune() {
  return Object.fromEntries(TUNE_CONTROLS.map((control) => [control.id, control.defaultValue]));
}
